from building import *
import os
cwd = GetCurrentDir()
sources = ['/edgi/pet_core.c', '/edgi/interaction_hold.c', '/edgi/storage.c',
           '/edgi/storage_journal.c', '/common/protocol.c', '/common/messages.c',
           '/common/reliable.c']
smif = os.path.normpath(os.path.join(cwd, '..', '..', 'libraries', 'components',
    'mtb-device-support-pse8xxgp', 'pdl', 'drivers', 'source'))
sources = [cwd + name for name in sources] + [
    os.path.join(smif, 'cy_smif.c'),
    os.path.join(smif, 'cy_smif_memslot.c'),
    os.path.join(smif, 'cy_smif_hb_flash.c'),
    os.path.join(smif, 'cy_smif_sfdp.c'),
    os.path.join(smif, 'cy_smif_memnum.c')]
group = DefineGroup('PetCore', sources, depend=[''], CPPPATH=[cwd])
Return('group')
