# 复制到：Edgi_Talk_Audio/applications/m33/
import os
from building import *

cwd = GetCurrentDir()
src = Glob('src/*.c')
Import('RTT_ROOT')

# Ensure LWIP headers are visible to this application.
# Important: RT-Thread makefile generation collects `CPPPATH` (not LOCAL_CPPPATH),
# so we set CPPPATH to make it appear in compiler -I options.
inc = [os.path.join(cwd, 'include')]
lwip_inc = os.path.join(RTT_ROOT, 'components', 'net', 'lwip', 'lwip-2.1.2', 'src', 'include')
inc.append(lwip_inc)

group = DefineGroup('edgi_m33_pack', src, depend=[''], CPPPATH=inc)

Return('group')
