# 复制到：Edgi_Talk_Audio/applications/m33/
import os
from building import *

cwd = GetCurrentDir()
src = Glob('src/*.c')
Import('RTT_ROOT')

# Ensure LWIP headers are visible to this application.
# Important: RT-Thread makefile generation collects `CPPPATH` (not LOCAL_CPPPATH),
# so we set CPPPATH to make it appear in compiler -I options.
inc = [os.path.join(cwd, 'include')]
shared_dir = os.path.normpath(os.path.join(cwd, '../../../pet_shared'))
inc.append(shared_dir)
lwip_inc = os.path.join(RTT_ROOT, 'components', 'net', 'lwip', 'lwip-2.1.2', 'src', 'include')
inc.append(lwip_inc)

group = DefineGroup('edgi_m33_pack', src, depend=[''], CPPPATH=inc)
# The M33 and M55 compiler ABIs differ, so never leave this shared source's
# object beside pet_shared where the other project could reuse it.
ring_target = os.path.normpath(os.path.join(
    cwd, '../../build/applications/m33/edgi_voice_ring_m33.o'))
ring_object = Env.Object(target=ring_target,
                         source=os.path.join(shared_dir, 'edgi_voice_ring.c'),
                         CPPPATH=inc)
result = group + ring_object

Return('result')
