import rtconfig
from building import *

cwd = GetCurrentDir()
shared = cwd + '/../../../pet_shared'
src = Glob('*.c') + [shared + '/edgi_voice_ring.c']
path = [cwd, shared]

group = DefineGroup('voice', src, depend = [''], CPPPATH = path)

Return('group')
