import rtconfig
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd, cwd + '/../../../pet_shared']

group = DefineGroup('voice', src, depend = [''], CPPPATH = path)

Return('group')
