/* Auto-generated by train_edgi_open_cnn.py */
#ifndef EDGI_MEL_CONFIG_H
#define EDGI_MEL_CONFIG_H

#define EDGI_MEL_SAMPLE_RATE_HZ  16000u
#define EDGI_MEL_WIN_SAMPLES     480u
#define EDGI_MEL_HOP_SAMPLES     320u
#define EDGI_MEL_CLIP_SAMPLES    16000u
#define EDGI_MEL_N_FFT           512u
#define EDGI_MEL_N_BANDS         40u
#define EDGI_MEL_N_FRAMES        49u

#endif /* EDGI_MEL_CONFIG_H */
